import type { Category } from "../types";

/**
 * TLN Mijn Digitale Landschap taxonomy
 * Hierarchical category structure for the Logistiek Appstore
 */
export const TLN_CATEGORIES: Category[] = [
  {
    id: "cat-thuisbasis",
    name: "Thuisbasis — Backoffice",
    slug: "thuisbasis-backoffice",
    description: "Software voor kantoor- en bedrijfsprocessen",
    icon: "Building2",
    parentId: null,
    sortOrder: 1,
    children: [
      {
        id: "cat-tms",
        name: "TMS",
        slug: "tms",
        description: "Transport Management System",
        icon: "Truck",
        parentId: "cat-thuisbasis",
        sortOrder: 1,
        children: [
          { id: "cat-tms-orders", name: "Orders administratie", slug: "orders-administratie", parentId: "cat-tms", sortOrder: 1 },
          { id: "cat-tms-ritplanning", name: "Ritplanning", slug: "tms-ritplanning", parentId: "cat-tms", sortOrder: 2 },
          { id: "cat-tms-routeplanning", name: "Routeplanning", slug: "routeplanning", parentId: "cat-tms", sortOrder: 3 },
          { id: "cat-tms-tarifering", name: "Tarifering", slug: "tarifering", parentId: "cat-tms", sortOrder: 4 },
          { id: "cat-tms-facturatie", name: "Facturatie", slug: "tms-facturatie", parentId: "cat-tms", sortOrder: 5 },
          { id: "cat-tms-cbs", name: "CBS module", slug: "cbs-module", parentId: "cat-tms", sortOrder: 6 },
          { id: "cat-tms-carbon", name: "Carbon Foot Printing", slug: "carbon-foot-printing", parentId: "cat-tms", sortOrder: 7 },
          { id: "cat-tms-wagenpark", name: "Wagenparkbeheer", slug: "wagenparkbeheer", parentId: "cat-tms", sortOrder: 8 },
          { id: "cat-tms-emballage", name: "Emballageretouren administratie", slug: "tms-emballageretouren", parentId: "cat-tms", sortOrder: 9 },
          { id: "cat-tms-klachten", name: "Klachten registratie", slug: "klachten-registratie", parentId: "cat-tms", sortOrder: 10 },
        ],
      },
      {
        id: "cat-ritplanning",
        name: "Route- & Ritplanning",
        slug: "route-ritplanning",
        description: "Geavanceerde planningssoftware",
        icon: "Route",
        parentId: "cat-thuisbasis",
        sortOrder: 2,
        children: [
          { id: "cat-rp-ritplanning", name: "Ritplanning", slug: "ritplanning", parentId: "cat-ritplanning", sortOrder: 1 },
          { id: "cat-rp-aps", name: "Advanced Planning Systeem (APS)", slug: "advanced-planning-systeem", parentId: "cat-ritplanning", sortOrder: 2 },
        ],
      },
      {
        id: "cat-fleet",
        name: "Fleet Management Software",
        slug: "fleet-management",
        description: "Wagenparkbeheer en vlootmanagement",
        icon: "Car",
        parentId: "cat-thuisbasis",
        sortOrder: 3,
        children: [
          { id: "cat-fleet-comm", name: "Communicatie backoffice — chauffeur", slug: "communicatie-backoffice-chauffeur", parentId: "cat-fleet", sortOrder: 1 },
          { id: "cat-fleet-track", name: "Voertuigvolg- en traceersysteem", slug: "voertuigvolg-traceersysteem", parentId: "cat-fleet", sortOrder: 2 },
          { id: "cat-fleet-cao", name: "CAO — salaris voorloop", slug: "cao-salaris-voorloop", parentId: "cat-fleet", sortOrder: 3 },
          { id: "cat-fleet-fuel", name: "Brandstofanalyse", slug: "brandstofanalyse", parentId: "cat-fleet", sortOrder: 4 },
          { id: "cat-fleet-tacho", name: "Tacho analyse", slug: "tacho-analyse", parentId: "cat-fleet", sortOrder: 5 },
          { id: "cat-fleet-driving", name: "Monitoren en analyseren van rijgedrag", slug: "rijgedrag-analyse", parentId: "cat-fleet", sortOrder: 6 },
        ],
      },
      {
        id: "cat-wms",
        name: "WMS",
        slug: "wms",
        description: "Warehouse Management System",
        icon: "Warehouse",
        parentId: "cat-thuisbasis",
        sortOrder: 4,
        children: [
          { id: "cat-wms-voorraad", name: "Voorraad beheer", slug: "voorraad-beheer", parentId: "cat-wms", sortOrder: 1 },
          { id: "cat-wms-inuit", name: "In- en uitslag", slug: "in-en-uitslag", parentId: "cat-wms", sortOrder: 2 },
          { id: "cat-wms-picking", name: "Orderpicking", slug: "orderpicking", parentId: "cat-wms", sortOrder: 3 },
          { id: "cat-wms-scanning", name: "Scanning", slug: "wms-scanning", parentId: "cat-wms", sortOrder: 4 },
          { id: "cat-wms-emballage", name: "Emballageretouren administratie", slug: "wms-emballageretouren", parentId: "cat-wms", sortOrder: 5 },
          { id: "cat-wms-douane", name: "Douane entrepot", slug: "douane-entrepot", parentId: "cat-wms", sortOrder: 6 },
          { id: "cat-wms-val", name: "VAL", slug: "val", parentId: "cat-wms", sortOrder: 7 },
          { id: "cat-wms-crossdock", name: "Crossdocking", slug: "crossdocking", parentId: "cat-wms", sortOrder: 8 },
          { id: "cat-wms-replenish", name: "Replenishment", slug: "replenishment", parentId: "cat-wms", sortOrder: 9 },
          { id: "cat-wms-dock", name: "Dock- & yard management", slug: "dock-yard-management", parentId: "cat-wms", sortOrder: 10 },
        ],
      },
      {
        id: "cat-crm",
        name: "CRM",
        slug: "crm",
        description: "Customer Relationship Management",
        icon: "Users",
        parentId: "cat-thuisbasis",
        sortOrder: 5,
        children: [
          { id: "cat-crm-marketing", name: "Marketing", slug: "marketing", parentId: "cat-crm", sortOrder: 1 },
          { id: "cat-crm-klachten", name: "Klachtenbeheer", slug: "klachtenbeheer", parentId: "cat-crm", sortOrder: 2 },
          { id: "cat-crm-docs", name: "Documentenbeheer", slug: "crm-documentenbeheer", parentId: "cat-crm", sortOrder: 3 },
          { id: "cat-crm-rapport", name: "Rapportage en analyse", slug: "crm-rapportage", parentId: "cat-crm", sortOrder: 4 },
          { id: "cat-crm-accounts", name: "Account- & contactenbeheer", slug: "account-contactenbeheer", parentId: "cat-crm", sortOrder: 5 },
          { id: "cat-crm-sales", name: "Sales — leadbeheer — offertes", slug: "sales-leadbeheer-offertes", parentId: "cat-crm", sortOrder: 6 },
        ],
      },
      {
        id: "cat-financieel",
        name: "Financieel",
        slug: "financieel",
        description: "Financiele software en administratie",
        icon: "Banknote",
        parentId: "cat-thuisbasis",
        sortOrder: 6,
        children: [
          { id: "cat-fin-boek", name: "Boekhouding", slug: "boekhouding", parentId: "cat-financieel", sortOrder: 1 },
          { id: "cat-fin-fact", name: "Facturatie", slug: "fin-facturatie", parentId: "cat-financieel", sortOrder: 2 },
          { id: "cat-fin-debcred", name: "Debiteuren- en crediteurenbeheer", slug: "debiteuren-crediteurenbeheer", parentId: "cat-financieel", sortOrder: 3 },
          { id: "cat-fin-kosten", name: "Kostenbeheer", slug: "kostenbeheer", parentId: "cat-financieel", sortOrder: 4 },
          { id: "cat-fin-rapport", name: "Rapportage en analyse", slug: "fin-rapportage", parentId: "cat-financieel", sortOrder: 5 },
          { id: "cat-fin-bank", name: "Bankintegratie", slug: "bankintegratie", parentId: "cat-financieel", sortOrder: 6 },
          { id: "cat-fin-belasting", name: "Belastingbeheer", slug: "belastingbeheer", parentId: "cat-financieel", sortOrder: 7 },
          { id: "cat-fin-budget", name: "Budgettering", slug: "budgettering", parentId: "cat-financieel", sortOrder: 8 },
          { id: "cat-fin-audit", name: "Auditing", slug: "auditing", parentId: "cat-financieel", sortOrder: 9 },
        ],
      },
      {
        id: "cat-hr",
        name: "HR-software",
        slug: "hr-software",
        description: "Human Resources en personeelsbeheer",
        icon: "UserCog",
        parentId: "cat-thuisbasis",
        sortOrder: 7,
        children: [
          { id: "cat-hr-personeel", name: "Personeelsadministratie", slug: "personeelsadministratie", parentId: "cat-hr", sortOrder: 1 },
          { id: "cat-hr-salaris", name: "Salarisadministratie", slug: "salarisadministratie", parentId: "cat-hr", sortOrder: 2 },
          { id: "cat-hr-verlof", name: "Verlofbeheer", slug: "verlofbeheer", parentId: "cat-hr", sortOrder: 3 },
          { id: "cat-hr-arbo", name: "Arbo", slug: "arbo", parentId: "cat-hr", sortOrder: 4 },
          { id: "cat-hr-portal", name: "Medewerkerportal", slug: "medewerkerportal", parentId: "cat-hr", sortOrder: 5 },
          { id: "cat-hr-prestatie", name: "Prestatie en beoordeling", slug: "prestatie-beoordeling", parentId: "cat-hr", sortOrder: 6 },
          { id: "cat-hr-werving", name: "Werving en selectie", slug: "werving-selectie", parentId: "cat-hr", sortOrder: 7 },
          { id: "cat-hr-training", name: "Training en ontwikkeling", slug: "training-ontwikkeling", parentId: "cat-hr", sortOrder: 8 },
        ],
      },
      {
        id: "cat-docmgmt",
        name: "Document Management",
        slug: "document-management",
        description: "Documentbeheer en scanning",
        icon: "FileText",
        parentId: "cat-thuisbasis",
        sortOrder: 8,
        children: [
          { id: "cat-doc-scanning", name: "Scanning", slug: "doc-scanning", parentId: "cat-docmgmt", sortOrder: 1 },
        ],
      },
      {
        id: "cat-website",
        name: "Website & Klantportal",
        slug: "website-klantportal",
        description: "Websites en klantportalen",
        icon: "Globe",
        parentId: "cat-thuisbasis",
        sortOrder: 9,
        children: [
          { id: "cat-web-website", name: "Website", slug: "website", parentId: "cat-website", sortOrder: 1 },
          { id: "cat-web-portal", name: "Klantenportal", slug: "klantenportal", parentId: "cat-website", sortOrder: 2 },
          { id: "cat-web-app", name: "Klanten app", slug: "klanten-app", parentId: "cat-website", sortOrder: 3 },
        ],
      },
    ],
  },
  {
    id: "cat-iaa",
    name: "Identificatie, Authenticatie & Autorisatie",
    slug: "identificatie-authenticatie-autorisatie",
    description: "Identiteits- en toegangsbeheer",
    icon: "ShieldCheck",
    parentId: null,
    sortOrder: 2,
    children: [
      { id: "cat-iaa-pas", name: "Toegangspas", slug: "toegangspas", parentId: "cat-iaa", sortOrder: 1 },
      { id: "cat-iaa-auth", name: "Authenticatiemiddelen", slug: "authenticatiemiddelen", parentId: "cat-iaa", sortOrder: 2 },
      { id: "cat-iaa-autorisatie", name: "Autorisatiemiddel", slug: "autorisatiemiddel", parentId: "cat-iaa", sortOrder: 3 },
      { id: "cat-iaa-id", name: "Identificatiemiddelen", slug: "identificatiemiddelen", parentId: "cat-iaa", sortOrder: 4 },
      { id: "cat-iaa-pwmgr", name: "Password manager", slug: "password-manager", parentId: "cat-iaa", sortOrder: 5 },
    ],
  },
  {
    id: "cat-cybersec",
    name: "Cyber Security",
    slug: "cyber-security",
    description: "Cyberveiligheid en beveiligingsoplossingen",
    icon: "Lock",
    parentId: null,
    sortOrder: 3,
  },
  {
    id: "cat-operations",
    name: "Uitvoering — Operations",
    slug: "uitvoering-operations",
    description: "Software voor de dagelijkse operatie",
    icon: "Cog",
    parentId: null,
    sortOrder: 4,
    children: [
      {
        id: "cat-nav",
        name: "Navigatiesoftware",
        slug: "navigatiesoftware",
        description: "Navigatie en routegeleiding",
        icon: "Navigation",
        parentId: "cat-operations",
        sortOrder: 1,
        children: [
          { id: "cat-nav-route", name: "Route navigatie", slug: "route-navigatie", parentId: "cat-nav", sortOrder: 1 },
          { id: "cat-nav-verkeer", name: "Verkeersinformatie", slug: "verkeersinformatie", parentId: "cat-nav", sortOrder: 2 },
          { id: "cat-nav-waarschuwing", name: "Weg waarschuwing", slug: "weg-waarschuwing", parentId: "cat-nav", sortOrder: 3 },
          { id: "cat-nav-beperkingen", name: "Voertuigbeperkingen", slug: "voertuigbeperkingen", parentId: "cat-nav", sortOrder: 4 },
          { id: "cat-nav-poi", name: "Points of interest", slug: "points-of-interest", parentId: "cat-nav", sortOrder: 5 },
        ],
      },
      {
        id: "cat-boordcomp",
        name: "Registratie & Verantwoording — Boordcomputer",
        slug: "boordcomputer",
        description: "Boordcomputer en registratiesoftware",
        icon: "Monitor",
        parentId: "cat-operations",
        sortOrder: 2,
        children: [
          { id: "cat-bc-uren", name: "Uren verantwoording", slug: "uren-verantwoording", parentId: "cat-boordcomp", sortOrder: 1 },
          { id: "cat-bc-opdrachten", name: "Opdrachten — vragenpad", slug: "opdrachten-vragenpad", parentId: "cat-boordcomp", sortOrder: 2 },
          { id: "cat-bc-tacho", name: "Tachograaf", slug: "bc-tachograaf", parentId: "cat-boordcomp", sortOrder: 3 },
          { id: "cat-bc-rijtijden", name: "Rijtijden — tacho", slug: "rijtijden-tacho", parentId: "cat-boordcomp", sortOrder: 4 },
          { id: "cat-bc-comm", name: "Communicatie", slug: "bc-communicatie", parentId: "cat-boordcomp", sortOrder: 5 },
          { id: "cat-bc-nav", name: "Navigatie", slug: "bc-navigatie", parentId: "cat-boordcomp", sortOrder: 6 },
          { id: "cat-bc-rijstijl", name: "Rijstijl", slug: "rijstijl", parentId: "cat-boordcomp", sortOrder: 7 },
          { id: "cat-bc-scanning", name: "Scanning", slug: "bc-scanning", parentId: "cat-boordcomp", sortOrder: 8 },
          { id: "cat-bc-tt", name: "Track & Trace orders", slug: "track-trace-orders", parentId: "cat-boordcomp", sortOrder: 9 },
          { id: "cat-bc-charter", name: "Charter app", slug: "charter-app", parentId: "cat-boordcomp", sortOrder: 10 },
          { id: "cat-bc-driver", name: "Driver app", slug: "driver-app", parentId: "cat-boordcomp", sortOrder: 11 },
        ],
      },
      {
        id: "cat-telematica",
        name: "Truck & Trailer Telematica",
        slug: "truck-trailer-telematica",
        description: "Voertuig- en trailertelematica",
        icon: "Radio",
        parentId: "cat-operations",
        sortOrder: 3,
        children: [
          { id: "cat-tel-fuel", name: "Brandstof", slug: "tel-brandstof", parentId: "cat-telematica", sortOrder: 1 },
          { id: "cat-tel-toegang", name: "Toegang — deur open/dicht", slug: "toegang-deur", parentId: "cat-telematica", sortOrder: 2 },
          { id: "cat-tel-tracking", name: "Tracking", slug: "tracking", parentId: "cat-telematica", sortOrder: 3 },
          { id: "cat-tel-temp", name: "Temperatuur- en vochtigheidsmonitoring", slug: "temperatuur-vochtigheid", parentId: "cat-telematica", sortOrder: 4 },
          { id: "cat-tel-rijgedrag", name: "Rijgedrag monitoring", slug: "rijgedrag-monitoring", parentId: "cat-telematica", sortOrder: 5 },
          { id: "cat-tel-diag", name: "Voertuig diagnostiek", slug: "voertuig-diagnostiek", parentId: "cat-telematica", sortOrder: 6 },
          { id: "cat-tel-tol", name: "Tol", slug: "tol", parentId: "cat-telematica", sortOrder: 7 },
          { id: "cat-tel-dashcam", name: "Videotelematica — dashcams", slug: "videotelematica-dashcams", parentId: "cat-telematica", sortOrder: 8 },
        ],
      },
      {
        id: "cat-tachograaf",
        name: "Tachograaf",
        slug: "tachograaf",
        icon: "Gauge",
        parentId: "cat-operations",
        sortOrder: 4,
        children: [
          { id: "cat-tacho-uitlees", name: "Tachograaf uitleesapparatuur", slug: "tachograaf-uitleesapparatuur", parentId: "cat-tachograaf", sortOrder: 1 },
        ],
      },
      {
        id: "cat-commmiddelen",
        name: "Communicatiemiddelen",
        slug: "communicatiemiddelen",
        icon: "Phone",
        parentId: "cat-operations",
        sortOrder: 5,
        children: [
          { id: "cat-comm-mobiel", name: "Mobiele telefonie", slug: "mobiele-telefonie", parentId: "cat-commmiddelen", sortOrder: 1 },
          { id: "cat-comm-berichten", name: "Berichtenverkeer", slug: "berichtenverkeer", parentId: "cat-commmiddelen", sortOrder: 2 },
        ],
      },
      {
        id: "cat-pod",
        name: "Proof of Delivery / Vrachtbrief",
        slug: "proof-of-delivery",
        description: "Afleverbewijzen en vrachtbrieven",
        icon: "ClipboardCheck",
        parentId: "cat-operations",
        sortOrder: 6,
        children: [
          { id: "cat-pod-ecmr", name: "eCMR", slug: "ecmr", parentId: "cat-pod", sortOrder: 1 },
          { id: "cat-pod-sign", name: "Sign on glass", slug: "sign-on-glass", parentId: "cat-pod", sortOrder: 2 },
          { id: "cat-pod-printer", name: "Printer vrachtbrief", slug: "printer-vrachtbrief", parentId: "cat-pod", sortOrder: 3 },
        ],
      },
    ],
  },
  {
    id: "cat-kos",
    name: "Klant — Overheid — Sector",
    slug: "klant-overheid-sector",
    description: "Integraties met klant-, overheids- en sectorportalen",
    icon: "Landmark",
    parentId: null,
    sortOrder: 5,
    children: [
      {
        id: "cat-overheid",
        name: "Overheidsportals",
        slug: "overheidsportals",
        icon: "Building",
        parentId: "cat-kos",
        sortOrder: 1,
        children: [
          { id: "cat-ov-belasting", name: "Belastingdienst", slug: "belastingdienst", parentId: "cat-overheid", sortOrder: 1 },
          { id: "cat-ov-kvk", name: "Kamer van Koophandel", slug: "kamer-van-koophandel", parentId: "cat-overheid", sortOrder: 2 },
          { id: "cat-ov-rvo", name: "RVO", slug: "rvo", parentId: "cat-overheid", sortOrder: 3 },
          { id: "cat-ov-cbs", name: "Centraal Bureau voor de Statistiek", slug: "cbs", parentId: "cat-overheid", sortOrder: 4 },
          { id: "cat-ov-nvwa", name: "NVWA", slug: "nvwa", parentId: "cat-overheid", sortOrder: 5 },
          { id: "cat-ov-ilt", name: "Inspectie Leefomgeving en Transport", slug: "inspectie-leefomgeving-transport", parentId: "cat-overheid", sortOrder: 6 },
        ],
      },
      {
        id: "cat-community",
        name: "Community Systemen",
        slug: "community-systemen",
        icon: "Network",
        parentId: "cat-kos",
        sortOrder: 2,
        children: [
          { id: "cat-comm-portbase", name: "Portbase", slug: "portbase", parentId: "cat-community", sortOrder: 1 },
          { id: "cat-comm-cargonaut", name: "CargoNaut", slug: "cargonaut", parentId: "cat-community", sortOrder: 2 },
        ],
      },
      {
        id: "cat-klant",
        name: "Klant- & Sectorspecifiek Systeem",
        slug: "klant-sector-systeem",
        icon: "Plug",
        parentId: "cat-kos",
        sortOrder: 3,
        children: [
          { id: "cat-klant-erp", name: "ERP klant", slug: "erp-klant", parentId: "cat-klant", sortOrder: 1 },
          { id: "cat-klant-portal", name: "Klant portal", slug: "klant-portal", parentId: "cat-klant", sortOrder: 2 },
          { id: "cat-klant-floriday", name: "Floriday", slug: "floriday", parentId: "cat-klant", sortOrder: 3 },
        ],
      },
      {
        id: "cat-douane",
        name: "Douane Software",
        slug: "douane-software",
        icon: "Shield",
        parentId: "cat-kos",
        sortOrder: 4,
        children: [
          { id: "cat-douane-uitvoer", name: "Uitvoeraangifte", slug: "uitvoeraangifte", parentId: "cat-douane", sortOrder: 1 },
          { id: "cat-douane-ncts", name: "NCTS", slug: "ncts", parentId: "cat-douane", sortOrder: 2 },
          { id: "cat-douane-accijns", name: "Accijns", slug: "accijns", parentId: "cat-douane", sortOrder: 3 },
          { id: "cat-douane-invoer", name: "Invoeraangifte", slug: "invoeraangifte", parentId: "cat-douane", sortOrder: 4 },
        ],
      },
    ],
  },
  {
    id: "cat-platforms",
    name: "Platforms — Communicatie & Integratie",
    slug: "platforms-communicatie-integratie",
    description: "Platform- en integratieoplossingen",
    icon: "Layers",
    parentId: null,
    sortOrder: 6,
    children: [
      { id: "cat-plat-visibility", name: "Visibility platforms", slug: "visibility-platforms", parentId: "cat-platforms", sortOrder: 1 },
      { id: "cat-plat-lading", name: "Lading uitwisseling", slug: "lading-uitwisseling", parentId: "cat-platforms", sortOrder: 2 },
      { id: "cat-plat-control", name: "Control Towers", slug: "control-towers", parentId: "cat-platforms", sortOrder: 3 },
      { id: "cat-plat-integratie", name: "Integratie platforms", slug: "integratie-platforms", parentId: "cat-platforms", sortOrder: 4 },
      { id: "cat-plat-comm", name: "Communicatie platforms", slug: "communicatie-platforms", parentId: "cat-platforms", sortOrder: 5 },
      {
        id: "cat-boeking",
        name: "Boeking Portaal",
        slug: "boeking-portaal",
        icon: "CalendarCheck",
        parentId: "cat-platforms",
        sortOrder: 6,
        children: [
          { id: "cat-boek-boottrein", name: "Boot — trein overtocht", slug: "boot-trein-overtocht", parentId: "cat-boeking", sortOrder: 1 },
          { id: "cat-boek-slot", name: "Boot — trein slotboeking", slug: "boot-trein-slotboeking", parentId: "cat-boeking", sortOrder: 2 },
          { id: "cat-boek-tijdslot", name: "Tijdslotboeking", slug: "tijdslotboeking", parentId: "cat-boeking", sortOrder: 3 },
        ],
      },
    ],
  },
  {
    id: "cat-rapportage",
    name: "Rapportage & Data-analyse",
    slug: "rapportage-data-analyse",
    description: "Business intelligence en data-analyse",
    icon: "BarChart3",
    parentId: null,
    sortOrder: 7,
    children: [
      {
        id: "cat-bizscans",
        name: "Business Scans",
        slug: "business-scans",
        icon: "ScanSearch",
        parentId: "cat-rapportage",
        sortOrder: 1,
        children: [
          { id: "cat-biz-itscan", name: "IT bedrijfs- en landschap scan", slug: "it-landschap-scan", parentId: "cat-bizscans", sortOrder: 1 },
        ],
      },
      {
        id: "cat-bi",
        name: "Business Intelligence & Reporting",
        slug: "business-intelligence-reporting",
        icon: "PieChart",
        parentId: "cat-rapportage",
        sortOrder: 2,
        children: [
          { id: "cat-bi-spreadsheet", name: "Spreadsheet", slug: "spreadsheet", parentId: "cat-bi", sortOrder: 1 },
          { id: "cat-bi-dataverw", name: "Data verwerking en analyse", slug: "data-verwerking-analyse", parentId: "cat-bi", sortOrder: 2 },
          { id: "cat-bi-integratie", name: "Data integratie", slug: "data-integratie", parentId: "cat-bi", sortOrder: 3 },
          { id: "cat-bi-visualisatie", name: "Data visualisatie", slug: "data-visualisatie", parentId: "cat-bi", sortOrder: 4 },
          { id: "cat-bi-dashboards", name: "Dashboards en KPI's", slug: "dashboards-kpis", parentId: "cat-bi", sortOrder: 5 },
          { id: "cat-bi-opslag", name: "Data opslag / warehousing", slug: "bi-data-opslag", parentId: "cat-bi", sortOrder: 6 },
        ],
      },
      {
        id: "cat-dataopslag",
        name: "Data Opslag — Data Warehousing",
        slug: "data-opslag-warehousing",
        icon: "Database",
        parentId: "cat-rapportage",
        sortOrder: 3,
        children: [
          { id: "cat-data-db", name: "Database", slug: "database", parentId: "cat-dataopslag", sortOrder: 1 },
          { id: "cat-data-warehouse", name: "Data Warehouse", slug: "data-warehouse", parentId: "cat-dataopslag", sortOrder: 2 },
          { id: "cat-data-query", name: "Query tooling", slug: "query-tooling", parentId: "cat-dataopslag", sortOrder: 3 },
        ],
      },
    ],
  },
];

/** Flatten the category tree into a single array */
export function flattenCategories(categories: Category[]): Category[] {
  const result: Category[] = [];
  function walk(cats: Category[]) {
    for (const cat of cats) {
      result.push(cat);
      if (cat.children) walk(cat.children);
    }
  }
  walk(categories);
  return result;
}

/** Find a category by slug in the tree */
export function findCategoryBySlug(slug: string, categories: Category[] = TLN_CATEGORIES): Category | undefined {
  for (const cat of categories) {
    if (cat.slug === slug) return cat;
    if (cat.children) {
      const found = findCategoryBySlug(slug, cat.children);
      if (found) return found;
    }
  }
  return undefined;
}
